### PR TITLE
fix(withdraw): add USD fiat values alongside amounts

### LINKED ISSUE #2644: Withdrawal confirmations are lacking detail
**To Reproduce**
1. Login
2. Open funded coin withdraw page
3. Click the button to see confirm modal.

**Screenshots**

Image

**Expected behavior**
While amount and fee is great information to be aware of, it would be a nice UX improvement to see the destination address and memo (where applicable).
Bonus points for copy/link (to explorer) icons alongside address and fiat value in brackets.

**Found in**
0.9.0 RC

**Environment:**

**Additional context**
Comparative examples in other products:

Image

Image

Image

Image

### PR DESCRIPTION
**Pull request by takenagain**
Closes #2644 by adding the last remaining detail: fiat amount alongside fee and transaction amounts.

## Mobile 

image

<details>
<summary>Further mobile examples</summary>

image

image

</details>

## Web/Desktop

image

image

---

> [!NOTE]
> Adds a reusable AssetAmountWithFiat widget and updates withdraw preview to show USD fiat for amount and fee with a responsive layout.
> 
> - **Shared Widgets**:
>   - `AssetAmountWithFiat`: new widget to display crypto amount with optional coin symbol and USD fiat (from SDK pricing), supporting auto-scroll and selectable text.
> - **Withdraw Preview UI**:
>   - `WithdrawPreviewDetails`: now uses `AssetAmountWithFiat` for `amount` and `fee` to show fiat values.
>   - Responsive layout with width-based row/stack switching and dynamic padding (`widthThreshold`, `minPadding`, `maxPadding`).
>   - Adjusted rows (label/value flex), and improved presentation of recipients and optional memo.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit fc2f90700ddd8b07e4be2ac6bea86f59cce48083. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by smk762** [comment]
Fiat value display confirmed, including long notes.

image

image

image

image

**Comment by takenagain** [comment]
> Comparing to [competing products](https://github.com/KomodoPlatform/komodo-wallet/issues/2644#issue-3080441692), I dont think we should use the negative `-` symbol

Done in [0f4bc96](https://github.com/KomodoPlatform/komodo-wallet/pull/3274/commits/0f4bc9632f2a2eea6b2eb78ac92171baac1e8d60)

File: lib/shared/widgets/asset_amount_with_fiat.dart [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+import 'package:komodo_ui_kit/komodo_ui_kit.dart';
+import 'package:web_dex/shared/utils/formatters.dart';
+import 'package:web_dex/shared/utils/utils.dart';
+
+/// A widget that displays an asset amount with its fiat value in parentheses.
+///
+/// Example output: "0.5 BTC ($15,234.50)"
+///
+/// The fiat value is only shown if pricing data is available from the SDK.
+class AssetAmountWithFiat extends StatelessWidget {
```
Comment (CharlVS) [inline lib/shared/widgets/asset_amount_with_fiat.dart:13]: Nit: prefer a name that better aligns with Flutter's naming conventions, making it clear that it is a widget. I assumed `AssetAmountWithFiat` was a data class when I first read it. 

e.g. `AssetAmountWithFiatDisplay`, `AssetAmountWithFiatText`, or otherwise if there's an existing widget  with a backwards-compatible signature, refactor to add an additional parameter to specify if the fiat value should be shown (ignore if such a widget doesn't exist)

File: lib/shared/widgets/asset_amount_with_fiat.dart [hunk 2]
```diff
@@ -0,0 +1,72 @@
+import 'package:decimal/decimal.dart';
+import 'package:flutter/material.dart';
+import 'package:komodo_defi_types/komodo_defi_types.dart';
+import 'package:komodo_ui_kit/komodo_ui_kit.dart';
+import 'package:web_dex/shared/utils/formatters.dart';
+import 'package:web_dex/shared/utils/utils.dart';
+
+/// A widget that displays an asset amount with its fiat value in parentheses.
```
Comment (CharlVS) [inline lib/shared/widgets/asset_amount_with_fiat.dart:8]: Nit: make it clear that the fiat value isn't passable and is automatically calculated from the SDK.
